# Generated by Django 3.1.2 on 2020-10-21 22:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeonorbit',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placeonorbit',
            name='purpose',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='placeonorbit',
            name='orbit',
            field=models.CharField(choices=[('LEO', 'LEO'), ('MEO', 'MEO'), ('GEO', 'GEO'), ('MEO', 'MEO'), ('MOON', 'MOON')], max_length=10, null=True),
        ),
    ]
