# Generated by Django 3.1.2 on 2020-10-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0003_auto_20201022_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
