# Generated by Django 3.1.2 on 2020-10-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0004_auto_20201022_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='country',
            field=models.CharField(default='USA', max_length=10),
        ),
    ]
