# Generated by Django 3.1.2 on 2020-10-21 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0005_producer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='launchsite',
            field=models.CharField(choices=[('Kennedy Space Center / USA', 'Kennedy Space Center / USA'), ('Boca Chica / USA', 'Boca Chica / USA'), ('Baikonur Cosmodrome / RUSSIA', 'Baikonur CosmodromE / RUSSIA'), ('Vostochny Cosmodrome / RUSSIA', 'Vostochny Cosmodrome / RUSSIA'), ('Wenchang Satellite Launch Center / CHINA', 'Wenchang Satellite Launch Center / CHINA'), ('Łeba-Rąbka / POLAND', 'Łeba-Rąbka / POLAND')], max_length=40),
        ),
        migrations.AlterField(
            model_name='flight',
            name='rocket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='space_app.rocket'),
        ),
        migrations.AlterField(
            model_name='launchsite',
            name='site',
            field=models.CharField(choices=[('Kennedy Space Center / USA', 'Kennedy Space Center / USA'), ('Boca Chica / USA', 'Boca Chica / USA'), ('Baikonur Cosmodrome / RUSSIA', 'Baikonur CosmodromE / RUSSIA'), ('Vostochny Cosmodrome / RUSSIA', 'Vostochny Cosmodrome / RUSSIA'), ('Wenchang Satellite Launch Center / CHINA', 'Wenchang Satellite Launch Center / CHINA'), ('Łeba-Rąbka / POLAND', 'Łeba-Rąbka / POLAND')], max_length=40),
        ),
    ]
