# Generated by Django 3.1.2 on 2020-10-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0006_auto_20201022_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
